baseURL = "https://liveunix.org"
languageCode = "en-us"
title = "liveunix"
theme = "after-dark"
enableRobotsTXT = true

[permalinks]
blog  = "blog/:slug/"
data  = "data/:slug/"

[params]
author = "Danilo Spinella"
description = "linux and bsd live iso informations"
dateformat = "Monday, Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"

[[menu.main]]
    name = "home"
    weight = "10"
    url = "/"
# [[menu.main]]
#     name= "whoami"
#     weight = 100
    # url = "/about/"
# [[menu.main]]
#     name= "blog"
#     weight = 100
#     url = "/blog"
[[menu.main]]
    name = "list"
    weight = 100
    url = "/data/"
[[menu.main]]
    name = "grep"
    weight = 200
    url = "/search/"
[[menu.main]]
    name= "git"
    weight = 300
    url = "https://github.com/liveunix/liveunix-data"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[blackfriday]
  hrefTargetBlank = true
  fractions = false
